name: e2e-android
on: push

jobs:
  e2e-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: Install dependencies
        run: npm install --frozen-lockfile --prefer-offline

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Run tests on emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 31
          arch: x86_64
          profile: pixel_5
          target: google_apis
          script: |
            npx detox build --configuration android.emu.release

            # Aguarda o ADB reconhecer o dispositivo
            adb wait-for-device
            until adb shell getprop sys.boot_completed | grep -m 1 '1'; do
              echo "Waiting for emulator to boot..."
              sleep 5
            done

            npx detox test --configuration android.emu.release --headless --record-logs all
